-- MySQL Script generated by MySQL Workbench
-- Fri Aug 22 06:31:21 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema philippine_cities
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `philippine_cities` ;
CREATE SCHEMA IF NOT EXISTS `philippine_cities` DEFAULT CHARACTER SET latin1 ;
USE `philippine_cities` ;

-- -----------------------------------------------------
-- Table `philippine_cities`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `philippine_cities`.`city` ;

CREATE TABLE IF NOT EXISTS `philippine_cities`.`city` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(10) NULL DEFAULT NULL,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1618
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
